server:
  extraArgs:
   - --insecure
  additionalApplications:
   - name: jruedas-tfm-podinfo
     project: default
     namespace: argocd
     source:
       repoURL: https://github.com/JRuedas/podinfo
       targetRevision: HEAD
       path: charts/podinfo
       helm:
        parameters:
        - name: ingress.enabled
          value: "true"
     destination:
       server: https://kubernetes.default.svc               
       namespace: jruedas-podinfo-dev
     syncPolicy:
       automated:
         prune: true
         selfHeal: true
       syncOptions:
        - ApplyOutOfSyncOnly=true
        - CreateNamespace=true
        - PrunePropagationPolicy=background
