dex:
  enabled: false
notifications:
  enabled: false
redis:
  enabled: false
applicationSet:
  enabled: false
server:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      "cert-manager.io/cluster-issuer": "letsencrypt-prod"
    hosts:
      - argocd.jruedas.dev
    https: true
    tls:
      - secretName: argocd-tls
        hosts:
          - argocd.jruedas.dev
  additionalApplications:
    - name: root-app
      namespace: argocd
      project: default
      source:
        path: applications/
        repoURL: https://github.com/JRuedas/tfm-argocd-apps.git
        targetRevision: HEAD
      destination:
        server: https://kubernetes.default.svc
        namespace: root-app
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - PrunePropagationPolicy=background
        retry:
          limit: 4
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s