server:
  extraArgs:
    - --insecure
  additionalApplications:
    - name: root-app
      namespace: argocd
      project: default
      source:
        path: applications/
        repoURL: https://github.com/JRuedas/tfm-argocd-apps.git
        targetRevision: HEAD
      destination:
        server: https://kubernetes.default.svc
        namespace: root-app
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - PrunePropagationPolicy=background
        retry:
          limit: 4
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s